/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TFM;

import java.util.HashSet;

/**
 *
 * @author Gabriel
 */
public class TimeManagementMenu extends javax.swing.JPanel implements TimeUpdateListener {
    
    //Simulation to which the time is going to be managed
    private Simulation simulation;

    /**
     * Creates new form TimeManagementMenu
     */
    public TimeManagementMenu(Simulation simulation) {
        this.simulation = simulation;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startJButton = new javax.swing.JButton();
        speedJButton = new javax.swing.JButton();
        pauseJButton = new javax.swing.JButton();
        timerTextField = new javax.swing.JTextField();
        endJButton = new javax.swing.JButton();

        startJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-play-50.png"))); // NOI18N
        startJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startJButtonMouseClicked(evt);
            }
        });
        startJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startJButtonActionPerformed(evt);
            }
        });

        speedJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-fast-forward-50.png"))); // NOI18N
        speedJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                speedJButtonMouseClicked(evt);
            }
        });
        speedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedJButtonActionPerformed(evt);
            }
        });

        pauseJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pause-50.png"))); // NOI18N
        pauseJButton.setToolTipText("");
        pauseJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pauseJButtonMouseClicked(evt);
            }
        });
        pauseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseJButtonActionPerformed(evt);
            }
        });

        timerTextField.setEditable(false);
        timerTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        timerTextField.setText("00:00:00");
        timerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerTextFieldActionPerformed(evt);
            }
        });

        endJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-stop-50.png"))); // NOI18N
        endJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endJButtonMouseClicked(evt);
            }
        });
        endJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(startJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(timerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pauseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(speedJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(endJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(startJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pauseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(speedJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startJButtonActionPerformed

    private void speedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speedJButtonActionPerformed

    private void pauseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseJButtonActionPerformed

    private void startJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startJButtonMouseClicked
        System.out.println("Simulation played");
        simulation.play();
    }//GEN-LAST:event_startJButtonMouseClicked

    private void pauseJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseJButtonMouseClicked
        System.out.println("Simulation paused");
        simulation.pause();
    }//GEN-LAST:event_pauseJButtonMouseClicked

    private void speedJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speedJButtonMouseClicked
        simulation.doubleSpeed();
    }//GEN-LAST:event_speedJButtonMouseClicked

    private void timerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerTextFieldActionPerformed

    }//GEN-LAST:event_timerTextFieldActionPerformed

    private void endJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endJButtonMouseClicked
        System.out.println("Simulation speed reset");
        simulation.setSpeed(1);
    }//GEN-LAST:event_endJButtonMouseClicked

    private void endJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endJButton;
    private javax.swing.JButton pauseJButton;
    private javax.swing.JButton speedJButton;
    private javax.swing.JButton startJButton;
    private javax.swing.JTextField timerTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onTimeUpdate(long simulationTime) {
        // Update the time display based on the simulation time
        String timeText = formatTime(simulationTime);
        timerTextField.setText(timeText);
    }
    
    private String formatTime(long simulationTime) {
        // Convert simulationTime to hours, minutes, and seconds, and format it as text
        // This is a simple placeholder. Implement conversion and formatting here.
        long hours = (simulationTime / (3600 * 1000)) % 24;
        long minutes = (simulationTime / (60 * 1000)) % 60;
        long seconds = (simulationTime / 1000) % 60;
        return String.format("%02d:%02d:%02d", hours, minutes, seconds);
    }
}
