package TFM.Routes;

import TFM.Routes.RouteController;
import java.io.File;

/**
 * Esta clase sirve para interactuar con el RouteController mediante una interfaz
 * Grafica
 * @author Jesus Lago
 */
public class RoutesMenu extends javax.swing.JPanel {

    //-------Parametros del text field---------//
    double cruiseAltitude=0; //ft
    double ascentRate=0; //ft/min
    double descentRate=0; //ft/min
    
    
    RouteController routeController;
    
    public RoutesMenu(RouteController routeController) {
        initComponents();
        
        this.routeController=routeController;
        
        
        //Busca y añade todos los archivos de ruta que existen en el directorio routes
        File directoryPath = new File("src/routes/");
        //List of all files and directories
        String contents[] = directoryPath.list();
        if(contents==null)
        {
            return;
        }
        
        //Add routes available
        for(int i = 0 ; i< contents.length;i++)
        {
            String routename = contents[i].substring(0, contents[i].length()-4);
            routeListCombo.insertItemAt(routename, i);
        }
        routeListCombo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        routeListCombo = new javax.swing.JComboBox<>();
        startRouteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cruiseAltitudeField = new javax.swing.JTextField();
        ascentRateField = new javax.swing.JTextField();
        descentRateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        altitudSlider = new javax.swing.JSlider();
        altitudScaleLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("Routes");

        routeListCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeListComboActionPerformed(evt);
            }
        });

        startRouteButton.setText("Start");
        startRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startRouteButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Vertical Profile");

        cruiseAltitudeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cruiseAltitudeField.setText("30000");

        ascentRateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ascentRateField.setText("2000");

        descentRateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        descentRateField.setText("-1000");

        jLabel4.setText("Altitud Scale:");

        altitudSlider.setMaximum(15);
        altitudSlider.setMinimum(1);
        altitudSlider.setValue(1);
        altitudSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altitudSlider.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        altitudSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                altitudSliderStateChanged(evt);
            }
        });

        altitudScaleLabel.setText("1");

        jLabel6.setText("Cruise Altitude (ft)");

        jLabel8.setText("Climb Rate (ft/min)");

        jLabel9.setText("Descent Rate (ft/min)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(altitudSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel6))
                                                .addGap(30, 30, 30))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ascentRateField)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(cruiseAltitudeField)
                                                .addGap(1, 1, 1))
                                            .addComponent(descentRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(startRouteButton))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(altitudScaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)))
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(routeListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(routeListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cruiseAltitudeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ascentRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descentRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startRouteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(altitudScaleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(altitudSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void altitudSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_altitudSliderStateChanged

        int altitudScale =  altitudSlider.getValue();
        routeController.setAltitudeScale(altitudScale);
        altitudScaleLabel.setText(Integer.toString(altitudScale));
    }//GEN-LAST:event_altitudSliderStateChanged

    private void startRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startRouteButtonActionPerformed

        //Obtiene el nombre de la ruta
        String routeName = (String) routeListCombo.getSelectedItem();
        if(routeName==null)
        {
            return;
        }
        
        //Añade un numero alfinal para distinguirlo si ya existe otra ruta con el nombre
        String fpname = routeName;
        int i = 1;
        while(routeController.containsNamedPlan(fpname))
        {
            fpname=routeName+Integer.toString(i);
            i++;
        }

        try{
            cruiseAltitude = Double.parseDouble(cruiseAltitudeField.getText());
            ascentRate = Double.parseDouble(ascentRateField.getText());
            descentRate = Double.parseDouble(descentRateField.getText());

        } catch(Exception e)
        {
            return;
        }

        routeController.startNew(fpname,"src/routes/"+routeName+".txt",cruiseAltitude,ascentRate,descentRate);
    }//GEN-LAST:event_startRouteButtonActionPerformed

    private void routeListComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeListComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeListComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altitudScaleLabel;
    private javax.swing.JSlider altitudSlider;
    private javax.swing.JTextField ascentRateField;
    private javax.swing.JTextField cruiseAltitudeField;
    private javax.swing.JTextField descentRateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> routeListCombo;
    private javax.swing.JButton startRouteButton;
    // End of variables declaration//GEN-END:variables
}
