/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TFM.GUI;

import TFM.Core.TrafficSimulated;
import TFM.Others.TrafficSimulationMap;
import TFM.utils.Config;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Gabriel
 */
public class LogsPanel extends javax.swing.JPanel {

    private TrafficSimulationMap tsm;
    /**
     * Creates new form LogsPanel
     * @param tsm
     */
    public LogsPanel(TrafficSimulationMap tsm) {
        this.tsm = tsm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generateLogsJButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(378, 55));

        generateLogsJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generateLogsJButton.setText("Generate Logs");
        generateLogsJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateLogsJButtonMouseClicked(evt);
            }
        });
        generateLogsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateLogsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(generateLogsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateLogsJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateLogsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateLogsJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateLogsJButtonActionPerformed

    private void generateLogsJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateLogsJButtonMouseClicked
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
        String timestamp = now.format(formatter);  

        System.out.println("GENERATE LOGS PRESSED");
        for (TrafficSimulated trafficSimulated : tsm.values()) {
            // Realizar alguna acción sobre cada objeto TrafficSimulated
            trafficSimulated.saveLogsToCsv(Config.logsPath+trafficSimulated.getHexCode()+"_"+timestamp+".csv");
        }
    }//GEN-LAST:event_generateLogsJButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateLogsJButton;
    // End of variables declaration//GEN-END:variables
}
